import { PageHeader } from "@/components/layout/PageHeader";
import { Card, CardHeader } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function SettingsPage() {
  const session = await auth();
  const [clubCount, mechanicCount, campaignCount] = await Promise.all([
    prisma.club.count(),
    prisma.mechanic.count(),
    prisma.campaign.count(),
  ]);

  return (
    <>
      <PageHeader title="Settings" subtitle="Account and portfolio configuration" />
      <div className="max-w-2xl space-y-6 px-8 py-6">
        <Card>
          <CardHeader title="Account" />
          <div className="space-y-3 text-sm">
            <Row label="Name" value={session?.user?.name ?? "—"} />
            <Row label="Email" value={session?.user?.email ?? "—"} />
            <Row label="Role" value={session?.user?.role ?? "—"} />
          </div>
        </Card>

        <Card>
          <CardHeader title="Portfolio" subtitle="Gym Group — Club Portfolio" />
          <div className="space-y-3 text-sm">
            <Row label="Clubs" value={String(clubCount)} />
            <Row label="Mechanics" value={String(mechanicCount)} />
            <Row label="Campaigns" value={String(campaignCount)} />
          </div>
        </Card>

        <Card>
          <CardHeader title="AI Configuration" />
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-semibold text-slate-800">Claude-powered advisor & recommendations</p>
              <p className="text-xs text-muted">AI Advisor, campaign recommendations, and alert narratives are generated by Claude.</p>
            </div>
            <Badge tone={process.env.ANTHROPIC_API_KEY && process.env.ANTHROPIC_API_KEY !== "placeholder" ? "accent" : "warning"}>
              {process.env.ANTHROPIC_API_KEY && process.env.ANTHROPIC_API_KEY !== "placeholder" ? "Connected" : "Not configured"}
            </Badge>
          </div>
        </Card>
      </div>
    </>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between border-b border-border pb-3 last:border-0 last:pb-0">
      <span className="text-muted">{label}</span>
      <span className="font-semibold text-slate-800">{value}</span>
    </div>
  );
}
